export const seedProducts = [
  {
    name: "Premium Wireless Headphones",
    category: "Electronics",
    price: 79.99,
    originalPrice: 129.99,
    stock: 50,
    rating: 4.5,
    reviews: 234,
    image: "/wireless-headphones.jpg",
    description: "High-quality wireless headphones with active noise cancellation, 30-hour battery life, and premium sound.",
    vendorId: "vendor_001",
  },
  {
    name: "Smart Fitness Watch",
    category: "Electronics",
    price: 199.99,
    originalPrice: 299.99,
    stock: 30,
    rating: 4.3,
    reviews: 156,
    image: "/modern-smartwatch.png",
    description: "Advanced fitness tracking with heart rate monitor, GPS, and 7-day battery.",
    vendorId: "vendor_001",
  },
  {
    name: "Professional Running Shoes",
    category: "Fashion",
    price: 89.99,
    originalPrice: 139.99,
    stock: 100,
    rating: 4.6,
    reviews: 412,
    image: "/running-shoes.jpg",
    description: "Lightweight and comfortable athletic shoes designed for marathon and distance running.",
    vendorId: "vendor_002",
  },
  {
    name: "Automatic Coffee Maker",
    category: "Home & Living",
    price: 49.99,
    originalPrice: 79.99,
    stock: 25,
    rating: 4.4,
    reviews: 189,
    image: "/coffee-maker.jpg",
    description: "Programmable coffee maker with thermal carafe and brew strength control.",
    vendorId: "vendor_003",
  },
  {
    name: "Fast USB-C Charging Cable",
    category: "Electronics",
    price: 12.99,
    originalPrice: 19.99,
    stock: 500,
    rating: 4.2,
    reviews: 567,
    image: "/usb-cable.jpg",
    description: "2-meter durable USB-C cable with fast charging support up to 100W.",
    vendorId: "vendor_001",
  },
  {
    name: "Premium Yoga Mat",
    category: "Sports & Outdoor",
    price: 34.99,
    originalPrice: 54.99,
    stock: 60,
    rating: 4.7,
    reviews: 278,
    image: "/yoga-mat.jpg",
    description: "Non-slip eco-friendly yoga mat with carrying strap, 6mm thick.",
    vendorId: "vendor_002",
  },
  {
    name: "LED Desk Lamp with USB",
    category: "Home & Living",
    price: 39.99,
    originalPrice: 59.99,
    stock: 45,
    rating: 4.5,
    reviews: 145,
    image: "/desk-lamp.jpg",
    description: "Adjustable LED desk lamp with USB charging port and 5 brightness levels.",
    vendorId: "vendor_003",
  },
  {
    name: "Waterproof Bluetooth Speaker",
    category: "Electronics",
    price: 59.99,
    originalPrice: 99.99,
    stock: 40,
    rating: 4.4,
    reviews: 334,
    image: "/portable-speaker.png",
    description: "Portable waterproof speaker with 360-degree sound and 12-hour battery.",
    vendorId: "vendor_001",
  },
  {
    name: "Stainless Steel Water Bottle",
    category: "Sports & Outdoor",
    price: 24.99,
    originalPrice: 39.99,
    stock: 75,
    rating: 4.6,
    reviews: 223,
    image: "/clear-water-bottle.png",
    description: "Insulated water bottle keeps drinks cold for 24 hours or hot for 12 hours.",
    vendorId: "vendor_002",
  },
  {
    name: "Minimalist Backpack",
    category: "Fashion",
    price: 44.99,
    originalPrice: 74.99,
    stock: 55,
    rating: 4.5,
    reviews: 198,
    image: "/colorful-backpack-on-wooden-table.png",
    description: "Durable and lightweight backpack perfect for travel and daily use.",
    vendorId: "vendor_002",
  },
  {
    name: "Wireless Phone Charger",
    category: "Electronics",
    price: 19.99,
    originalPrice: 29.99,
    stock: 120,
    rating: 4.3,
    reviews: 412,
    image: "/phone-charger.jpg",
    description: "Fast 15W wireless charging pad compatible with all Qi-enabled devices.",
    vendorId: "vendor_001",
  },
  {
    name: "Organic Cotton T-Shirt",
    category: "Fashion",
    price: 29.99,
    originalPrice: 49.99,
    stock: 200,
    rating: 4.4,
    reviews: 156,
    image: "/plain-white-tshirt.png",
    description: "Comfortable 100% organic cotton t-shirt in various colors.",
    vendorId: "vendor_002",
  },
];

export const seedOffers = [
  {
    code: "SAVE20",
    discount: 20,
    type: "percentage",
    description: "Save 20% on your purchase",
    maxUses: 100,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
  },
  {
    code: "FLAT50",
    discount: 50,
    type: "fixed",
    description: "Get $50 off on orders over $200",
    maxUses: 50,
    expiresAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
  },
  {
    code: "SUMMER30",
    discount: 30,
    type: "percentage",
    description: "Summer special - 30% off selected items",
    maxUses: 75,
    expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
  },
];

export const sampleUsers = [
  {
    email: "admin@example.com",
    password: "admin123",
    name: "Admin User",
    role: "admin",
  },
  {
    email: "vendor@example.com",
    password: "vendor123",
    name: "Vendor User",
    role: "vendor",
  },
  {
    email: "customer@example.com",
    password: "customer123",
    name: "Customer User",
    role: "customer",
  },
];
